import { InvestigationCase, InvestigationEntity, InvestigationRelationship } from '../types/investigation';

export const SEED_CASE: InvestigationCase = {
  id: 'case_blackwood_2026',
  title: 'Operation Blackwood: The Shadow Syndicate',
  caseNumber: 'CR-2026-0941',
  description: 'Multi-jurisdictional syndicate inquiry into art theft, offshore shell corporations, and coordinated logistical movements centered around Pier 9.',
  status: 'active',
  priority: 'critical',
  leadInvestigator: 'Inspector Dev Sharma',
  jurisdiction: 'CID Special Operations & Cyber-Forensics',
  incidentDate: '2026-09-01T21:30:00Z',
  createdAt: '2026-09-02T08:00:00Z',
  updatedAt: '2026-09-09T22:00:00Z',
  tags: ['syndicate', 'art_theft', 'shell_companies', 'forensics', 'priority_lead'],
};

export const SEED_ENTITIES: InvestigationEntity[] = [
  {
    id: 'ent_scene',
    caseId: SEED_CASE.id,
    type: 'location',
    label: 'Pier 9 Warehouse Scene',
    aliases: ['Dock 9 Vault', 'Warehouse 12'],
    attributes: { address: 'Pier 9, North Dock Basin', coordinates: '18.9431, 72.8412' },
    confidence: 1.0,
    status: 'verified_source',
    provenance: {
      sourceId: 'fir_01',
      sourceType: 'fir',
      sourceTitle: 'FIR #401/2026 — Dock Break-in',
      timestamp: '2026-09-01T22:15:00Z',
      confidence: 1.0,
    },
    boardPosition: { x: 0, y: 0, rotation: 0.02 },
    visualType: 'photo',
    notes: 'Primary point of intrusion. High-security steel gate breached via thermal lance.',
    tags: ['crime_scene', 'dock', 'breach'],
    createdAt: '2026-09-02T09:00:00Z',
    updatedAt: '2026-09-02T09:00:00Z',
  },
  {
    id: 'ent_marlowe',
    caseId: SEED_CASE.id,
    type: 'person',
    label: 'Julian Marlowe',
    aliases: ['The Antiquarian', 'J. M. Vane'],
    attributes: { age: 48, occupation: 'High-end Art & Antiquities Dealer', nationality: 'UK/India dual' },
    confidence: 0.94,
    status: 'investigator_confirmed',
    provenance: {
      sourceId: 'intel_doc_2',
      sourceType: 'surveillance',
      sourceTitle: 'Undercover Surveillance Dossier #12',
      confidence: 0.94,
    },
    boardPosition: { x: -28, y: 14, rotation: -0.05 },
    visualType: 'suspect',
    notes: 'Primary financier of syndicate acquisitions. Operates Marlowe Fine Arts gallery.',
    tags: ['suspect', 'financier', 'high_influence'],
    createdAt: '2026-09-02T09:30:00Z',
    updatedAt: '2026-09-03T11:00:00Z',
  },
  {
    id: 'ent_vance',
    caseId: SEED_CASE.id,
    type: 'person',
    label: 'Daniel Vance',
    aliases: ['Danny V', 'The Courier'],
    attributes: { age: 34, occupation: 'Freight Logistics Coordinator' },
    confidence: 0.91,
    status: 'investigator_confirmed',
    provenance: {
      sourceId: 'cdr_01',
      sourceType: 'cdr',
      sourceTitle: 'Cell Tower Triangulation - Pier 9',
      confidence: 0.91,
    },
    boardPosition: { x: -16, y: -16, rotation: 0.04 },
    visualType: 'suspect',
    notes: 'Key logistical intermediary. Cell phone pinged at Pier 9 at 21:28, 4 minutes before alarm.',
    tags: ['suspect', 'courier', 'bridge'],
    createdAt: '2026-09-02T10:00:00Z',
    updatedAt: '2026-09-03T12:00:00Z',
  },
  {
    id: 'ent_elena',
    caseId: SEED_CASE.id,
    type: 'person',
    label: 'Elena Rostova',
    aliases: ['The Broker', 'Helena R.'],
    attributes: { occupation: 'Offshore Wealth Consultant', residence: 'Bandra West' },
    confidence: 0.88,
    status: 'investigator_confirmed',
    provenance: {
      sourceId: 'bank_01',
      sourceType: 'bank_record',
      sourceTitle: 'Financial Intelligence Unit STR-882',
      confidence: 0.88,
    },
    boardPosition: { x: 26, y: 16, rotation: -0.03 },
    visualType: 'suspect',
    notes: 'Manages escrow accounts routing payments from buyers to the logistics team.',
    tags: ['broker', 'financial', 'intermediary'],
    createdAt: '2026-09-02T11:00:00Z',
    updatedAt: '2026-09-04T15:00:00Z',
  },
  {
    id: 'ent_shell_co',
    caseId: SEED_CASE.id,
    type: 'organization',
    label: 'Apex Maritime Holdings Ltd',
    aliases: ['Apex Shipping', 'AMH Group'],
    attributes: { registration: 'BVI-889124', jurisdiction: 'Tortola / Dubai' },
    confidence: 0.95,
    status: 'verified_source',
    provenance: {
      sourceId: 'bank_01',
      sourceType: 'bank_record',
      sourceTitle: 'Corporate Registry filings',
      confidence: 0.95,
    },
    boardPosition: { x: 38, y: -12, rotation: 0.01 },
    visualType: 'doc',
    notes: 'Paper corporation used to lease customs clearance containers at Pier 9.',
    tags: ['organization', 'shell_company'],
    createdAt: '2026-09-02T12:00:00Z',
    updatedAt: '2026-09-04T16:00:00Z',
  },
  {
    id: 'ent_burner',
    caseId: SEED_CASE.id,
    type: 'phone',
    label: 'Burner Phone (+91 98112-44120)',
    aliases: ['Target Line #3'],
    attributes: { imei: '864299041239851', carrier: 'Airtel Prepaid' },
    confidence: 0.89,
    status: 'verified_source',
    provenance: {
      sourceId: 'cdr_01',
      sourceType: 'cdr',
      sourceTitle: 'Tower Dump Analysis',
      confidence: 0.89,
    },
    boardPosition: { x: -38, y: -2, rotation: -0.06 },
    visualType: 'sticky',
    notes: 'Only activated 48 hours prior to the dock incident. Contacted Daniel Vance 14 times.',
    tags: ['communication', 'burner'],
    createdAt: '2026-09-02T14:00:00Z',
    updatedAt: '2026-09-05T09:00:00Z',
  },
  {
    id: 'ent_vehicle',
    caseId: SEED_CASE.id,
    type: 'vehicle',
    label: 'Red Sedan (MH-01-BX-4912)',
    aliases: ['Getaway Vehicle'],
    attributes: { make: 'Honda Civic', color: 'Crimson Red', stolen: true },
    confidence: 0.87,
    status: 'verified_source',
    provenance: {
      sourceId: 'surv_01',
      sourceType: 'surveillance',
      sourceTitle: 'Toll Plaza CCTV Footage',
      confidence: 0.87,
    },
    boardPosition: { x: 10, y: -24, rotation: 0.05 },
    visualType: 'map',
    notes: 'Captured fleeing south towards expressway at 21:42 with headlights off.',
    tags: ['vehicle', 'cctv', 'transit'],
    createdAt: '2026-09-03T10:00:00Z',
    updatedAt: '2026-09-05T14:00:00Z',
  },
  {
    id: 'ent_print',
    caseId: SEED_CASE.id,
    type: 'evidence_item',
    label: 'Latent Fingerprint #LP-4',
    aliases: ['Right Index Loop'],
    attributes: { ridgeCount: 14, surface: 'Steel Padlock', recoveredBy: 'Forensics Unit 4' },
    confidence: 0.96,
    status: 'verified_source',
    provenance: {
      sourceId: 'for_01',
      sourceType: 'forensic',
      sourceTitle: 'AFIS Ballistics & Latent Match Report',
      confidence: 0.96,
    },
    boardPosition: { x: -12, y: 22, rotation: -0.02 },
    visualType: 'print',
    notes: 'Recovered from discarded padlock shackle. Partial match to Daniel Vance.',
    tags: ['forensic', 'fingerprint'],
    createdAt: '2026-09-03T11:00:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 'ent_transaction',
    caseId: SEED_CASE.id,
    type: 'account',
    label: 'Wire Transfer ($450,000)',
    aliases: ['Tx Ref #SWIFT-99120'],
    attributes: { amount: 450000, currency: 'USD', bank: 'Standard International Zurich' },
    confidence: 0.93,
    status: 'verified_source',
    provenance: {
      sourceId: 'bank_01',
      sourceType: 'bank_record',
      sourceTitle: 'Suspicious Transaction Report FIU-IND',
      confidence: 0.93,
    },
    boardPosition: { x: 18, y: 28, rotation: 0.03 },
    visualType: 'doc',
    notes: 'Dispatched from Apex Maritime Holdings to Elena Rostova client account.',
    tags: ['financial', 'wire_transfer'],
    createdAt: '2026-09-04T08:00:00Z',
    updatedAt: '2026-09-04T08:00:00Z',
  },
  {
    id: 'ent_bag',
    caseId: SEED_CASE.id,
    type: 'evidence_item',
    label: 'Titanium Lockpick & Torch',
    aliases: ['Item #EB-08'],
    attributes: { manufacturer: 'Custom German Tooling', sootPresent: true },
    confidence: 0.98,
    status: 'verified_source',
    provenance: {
      sourceId: 'fir_01',
      sourceType: 'forensic',
      sourceTitle: 'Evidence Locker Tag #EB-08',
      confidence: 0.98,
    },
    boardPosition: { x: -2, y: -14, rotation: -0.04 },
    visualType: 'bag',
    notes: 'Abandoned under forklift in Sector B. Traces of cobalt paint matching vault exterior.',
    tags: ['physical_evidence', 'tool'],
    createdAt: '2026-09-02T13:00:00Z',
    updatedAt: '2026-09-02T13:00:00Z',
  },
];

export const SEED_RELATIONSHIPS: InvestigationRelationship[] = [
  {
    id: 'rel_1',
    caseId: SEED_CASE.id,
    sourceId: 'ent_marlowe',
    targetId: 'ent_vance',
    predicate: 'COMMUNICATED_WITH',
    label: 'Dispatched instructions',
    weight: 14,
    confidence: 0.92,
    status: 'verified_source',
    threadColor: 'crimson',
    validFrom: '2026-08-28T00:00:00Z',
    validTo: '2026-09-02T00:00:00Z',
    provenance: {
      sourceId: 'cdr_01',
      sourceType: 'cdr',
      sourceTitle: 'CDR Log #9012',
      confidence: 0.92,
    },
    notes: '14 encrypted voice calls logged between Marlowe and Vance across 72 hours.',
    manuallyConfirmed: true,
    createdAt: '2026-09-03T10:00:00Z',
    updatedAt: '2026-09-03T10:00:00Z',
  },
  {
    id: 'rel_2',
    caseId: SEED_CASE.id,
    sourceId: 'ent_vance',
    targetId: 'ent_scene',
    predicate: 'LOCATED_AT',
    label: 'Present during breach',
    weight: 5,
    confidence: 0.91,
    status: 'verified_source',
    threadColor: 'crimson',
    validFrom: '2026-09-01T21:00:00Z',
    validTo: '2026-09-01T22:00:00Z',
    provenance: {
      sourceId: 'cdr_01',
      sourceType: 'cdr',
      sourceTitle: 'Tower Azimuth triangulation',
      confidence: 0.91,
    },
    notes: 'Device confirmed in Sector 4 azimuth covering Pier 9 entry.',
    manuallyConfirmed: true,
    createdAt: '2026-09-03T11:00:00Z',
    updatedAt: '2026-09-03T11:00:00Z',
  },
  {
    id: 'rel_3',
    caseId: SEED_CASE.id,
    sourceId: 'ent_vance',
    targetId: 'ent_print',
    predicate: 'ASSOCIATED_WITH',
    label: 'AFIS biometric match',
    weight: 1,
    confidence: 0.96,
    status: 'verified_source',
    threadColor: 'twine',
    provenance: {
      sourceId: 'for_01',
      sourceType: 'forensic',
      sourceTitle: 'AFIS Match Card #499',
      confidence: 0.96,
    },
    notes: '99.4% probability match to Vance left thumb.',
    manuallyConfirmed: true,
    createdAt: '2026-09-04T09:00:00Z',
    updatedAt: '2026-09-04T09:00:00Z',
  },
  {
    id: 'rel_4',
    caseId: SEED_CASE.id,
    sourceId: 'ent_marlowe',
    targetId: 'ent_shell_co',
    predicate: 'OWNS',
    label: 'Beneficial Owner',
    weight: 1,
    confidence: 0.95,
    status: 'investigator_confirmed',
    threadColor: 'cobalt',
    provenance: {
      sourceId: 'bank_01',
      sourceType: 'bank_record',
      sourceTitle: 'BVI Registry beneficial ownership disclosure',
      confidence: 0.95,
    },
    notes: 'Shares held through nominee trustee.',
    manuallyConfirmed: true,
    createdAt: '2026-09-04T10:00:00Z',
    updatedAt: '2026-09-04T10:00:00Z',
  },
  {
    id: 'rel_5',
    caseId: SEED_CASE.id,
    sourceId: 'ent_shell_co',
    targetId: 'ent_transaction',
    predicate: 'TRANSFERRED_FUNDS',
    label: '$450,000 Escrow wire',
    weight: 450000,
    confidence: 0.98,
    status: 'verified_source',
    threadColor: 'cobalt',
    provenance: {
      sourceId: 'bank_01',
      sourceType: 'bank_record',
      sourceTitle: 'SWIFT wire trace',
      confidence: 0.98,
    },
    notes: 'Immediate debit after stolen artifacts were cataloged.',
    manuallyConfirmed: true,
    createdAt: '2026-09-04T12:00:00Z',
    updatedAt: '2026-09-04T12:00:00Z',
  },
  {
    id: 'rel_6',
    caseId: SEED_CASE.id,
    sourceId: 'ent_transaction',
    targetId: 'ent_elena',
    predicate: 'TRANSFERRED_FUNDS',
    label: 'Deposited to retainer',
    weight: 450000,
    confidence: 0.94,
    status: 'verified_source',
    threadColor: 'cobalt',
    provenance: {
      sourceId: 'bank_01',
      sourceType: 'bank_record',
      sourceTitle: 'HDFC Bank Account Ledger',
      confidence: 0.94,
    },
    notes: 'Received into Rostova Consulting escrow retainer.',
    manuallyConfirmed: true,
    createdAt: '2026-09-04T14:00:00Z',
    updatedAt: '2026-09-04T14:00:00Z',
  },
  {
    id: 'rel_7',
    caseId: SEED_CASE.id,
    sourceId: 'ent_elena',
    targetId: 'ent_marlowe',
    predicate: 'ASSOCIATED_WITH',
    label: 'Private Art Broker',
    weight: 6,
    confidence: 0.88,
    status: 'investigator_confirmed',
    threadColor: 'shadow',
    provenance: {
      sourceId: 'intel_doc_2',
      sourceType: 'surveillance',
      sourceTitle: 'Surveillance log: Royal Yacht Club meeting',
      confidence: 0.88,
    },
    notes: 'Met at yacht club 4 days prior to heist.',
    manuallyConfirmed: true,
    createdAt: '2026-09-04T15:00:00Z',
    updatedAt: '2026-09-04T15:00:00Z',
  },
  {
    id: 'rel_8',
    caseId: SEED_CASE.id,
    sourceId: 'ent_burner',
    targetId: 'ent_vance',
    predicate: 'CALLED',
    label: '14 Calls prior to heist',
    weight: 14,
    confidence: 0.89,
    status: 'verified_source',
    threadColor: 'crimson',
    provenance: {
      sourceId: 'cdr_01',
      sourceType: 'cdr',
      sourceTitle: 'CDR Call Log',
      confidence: 0.89,
    },
    notes: 'All calls lasted under 45 seconds.',
    manuallyConfirmed: true,
    createdAt: '2026-09-05T09:00:00Z',
    updatedAt: '2026-09-05T09:00:00Z',
  },
  {
    id: 'rel_9',
    caseId: SEED_CASE.id,
    sourceId: 'ent_vance',
    targetId: 'ent_vehicle',
    predicate: 'TRAVELED_TO',
    label: 'Fled scene in Honda',
    weight: 1,
    confidence: 0.87,
    status: 'investigator_confirmed',
    threadColor: 'twine',
    provenance: {
      sourceId: 'surv_01',
      sourceType: 'surveillance',
      sourceTitle: 'Traffic camera 400m south of dock',
      confidence: 0.87,
    },
    notes: 'Driver matches Vance physical profile.',
    manuallyConfirmed: true,
    createdAt: '2026-09-05T14:00:00Z',
    updatedAt: '2026-09-05T14:00:00Z',
  },
  {
    id: 'rel_10',
    caseId: SEED_CASE.id,
    sourceId: 'ent_bag',
    targetId: 'ent_scene',
    predicate: 'LOCATED_AT',
    label: 'Recovered at point of breach',
    weight: 1,
    confidence: 0.98,
    status: 'verified_source',
    threadColor: 'shadow',
    provenance: {
      sourceId: 'fir_01',
      sourceType: 'forensic',
      sourceTitle: 'CSI Physical Recovery Receipt',
      confidence: 0.98,
    },
    notes: 'Found beside severed padlock.',
    manuallyConfirmed: true,
    createdAt: '2026-09-02T13:00:00Z',
    updatedAt: '2026-09-02T13:00:00Z',
  },
];
